# A1 — model + projection matrices

Fix the projection sign. GAMES101 uses zNear, zFar as **positive distances** in front of the camera, camera looks down -z.

In [1]:
import numpy as np

def get_model_matrix(angle_deg):
    a = np.deg2rad(angle_deg)
    c, s = np.cos(a), np.sin(a)
    return np.array([[c, -s, 0, 0],
                     [s,  c, 0, 0],
                     [0,  0, 1, 0],
                     [0,  0, 0, 1]])

def get_projection_matrix(fov_deg, aspect, zN, zF):
    # camera looks along -z, so the numbers zN, zF are positive distances
    n, f = -zN, -zF
    t = zN * np.tan(np.deg2rad(fov_deg) / 2)
    r = t * aspect
    persp2ortho = np.array([[n, 0,     0,      0],
                            [0, n,     0,      0],
                            [0, 0, n + f, -n * f],
                            [0, 0,     1,      0]])
    ortho = np.array([[1/r, 0,           0,             0],
                      [0, 1/t,           0,             0],
                      [0,   0, 2/(n - f), -(n + f)/(n - f)],
                      [0,   0,           0,             1]])
    return ortho @ persp2ortho


## Bonus — Rodrigues, arbitrary axis

In [2]:
def get_rotation(axis, angle_deg):
    a = np.deg2rad(angle_deg)
    axis = axis / np.linalg.norm(axis)
    x, y, z = axis
    K = np.array([[0, -z, y],
                  [z,  0, -x],
                  [-y, x, 0]])
    R3 = np.eye(3) + np.sin(a) * K + (1 - np.cos(a)) * (K @ K)
    R = np.eye(4)
    R[:3, :3] = R3
    return R

print(get_rotation(np.array([0, 0, 1.0]), 90).round(3))


[[ 0. -1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
